[package]
name = "immt-shtml"
version = "0.0.1"
edition = "2021"

[lints]
workspace = true

[dependencies]
const_format = "0.2"
lazy_static = "1.5"
immt-api = { workspace=true }
kuchikiki = "0.8.2"
html5ever = "0.26.0" # needs to match kuchikiki precisely, for some reason
tendril = "0"