[package]
name = "math-archives"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[features]
## Enables RDF support
rdf = ["ftml-uris/rdf", "dep:ulo"]
## wasm
wasm = ["dep:tsify", "dep:wasm-bindgen"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "--cfg",
    "docsrs",
    "-Zunstable-options",
    "--generate-link-to-definition",
    "--html-in-header",
    "doc/katex-header.html",
    "--html-in-header",
    "doc/docs.html",
]
# cargo +nightly doc --no-deps --all-features --release --open

[build-dependencies]
rustc_version = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
#rstest = { workspace = true }
#criterion = { workspace = true }

[dependencies]
document-features = { workspace = true }
ftml-ontology = { workspace = true }
ftml-backend = { workspace = true }
ftml-uris = { workspace = true, features = ["interned"] }

inventory = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
smallvec = { workspace = true }
tracing = { workspace = true }
simple-home-dir = { workspace = true }
filetime = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
parking_lot = { workspace = true }
either = { workspace = true }
walkdir = { workspace = true }
const_format = { workspace = true }
bincode = { workspace = true }
triomphe = { workspace = true }

# orx-parallel = { workspace = true }
# # This is faster:
spliter = { workspace = true }
rayon = { workspace = true }

ulo = { workspace = true, optional = true }
tsify = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
