[package]
name = "ftml-solver"
version = "0.0.1"
edition = "2024"

[lints]
workspace = true

[dependencies]
flams-math-archives = {workspace=true}
ftml-uris = {workspace = true}
ftml-ontology = {workspace = true}
ftml-solver-trace = {workspace = true,features=["colors"]}
rayon = {workspace = true}
parking_lot = {workspace = true}
smallvec = {workspace = true}
rustc-hash = {workspace = true}
dashmap = {workspace = true}
either = {workspace = true}
tracing = {workspace = true}
paste = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
inventory = {workspace = true}

#anstyle = "1"
enable-ansi-support = {version="0.3"}

tracing-subscriber = {workspace = true}
stacker = "0.1"
bytesize = {workspace = true}
