[package]
name = "flams-router-content"
version = "0.0.1"
edition = "2024"

[lints]
workspace = true

[features]
ssr = [
    "leptos/ssr",
    "thaw/ssr",
    "ftml-viewer-components/ssr",
    "flams-web-utils/ssr",
    "dep:flams-system",
    "dep:leptos_axum",
    "dep:http",
    "dep:flams-lsp",
    "dep:tokio",
    "dep:paste",
    "dep:smallvec",
]
hydrate = [
    "leptos/hydrate",
    "thaw/hydrate",
    "ftml-viewer-components/hydrate",
    "flams-web-utils/hydrate",
]
docs-only = []

[dependencies]
flams-ontology = { workspace = true, features = ["serde"] }
flams-utils = { workspace = true }
ftml-viewer-components = { workspace = true }
flams-web-utils = { workspace = true }
flams-router-base = { workspace = true }
flams-system = { workspace = true, optional = true }
flams-lsp = { workspace = true, optional = true }

leptos = { workspace = true }
leptos_meta = { workspace = true }
leptos_router = { workspace = true }
thaw = { workspace = true }
serde = { workspace = true }
either = { workspace = true }
tracing = { workspace = true }
lazy_static = { workspace = true }

tokio = { workspace = true, optional = true }
paste = { workspace = true, optional = true }
smallvec = { workspace = true, optional = true }
leptos_axum = { workspace = true,optional=true }
http = { workspace = true,optional=true }
