[package]
name = "flams-router-content"
version = "0.0.1"
edition = "2024"

[lints]
workspace = true

[features]
ssr = [
    "leptos/ssr",
    "thaw/ssr",
    "ftml-leptos/ssr",
    "flams-web-utils/ssr",
    "flams-router-base/ssr",
    "dep:flams-system",
    "dep:flams-math-archives",
    "dep:leptos_axum",
    "dep:http",
    "dep:flams-lsp",
    "dep:tokio",
    "dep:paste",
    "dep:smallvec",
    "dep:ulo",
]
hydrate = [
    "leptos/hydrate",
    "thaw/hydrate",
    "ftml-leptos/hydrate",
    "flams-web-utils/hydrate",
    "ftml-backend/cached",
]
docs-only = []

[dependencies]
ftml-uris = { workspace = true, features = ["leptos"] }
ftml-ontology = { workspace = true, features = ["serde"] }
ftml-leptos = { workspace = true }
ftml-dom = { workspace = true }
ftml-backend = { workspace = true, features = ["server_fn"] }

flams-utils = { workspace = true }
flams-web-utils = { workspace = true }
flams-router-base = { workspace = true }
flams-system = { workspace = true, optional = true }
flams-math-archives = { workspace = true, optional = true }
flams-lsp = { workspace = true, optional = true }
ulo = { workspace = true, optional = true }

leptos = { workspace = true }
leptos_meta = { workspace = true }
leptos_router = { workspace = true }
thaw = { workspace = true }
serde = { workspace = true }
either = { workspace = true }
tracing = { workspace = true }
lazy_static = { workspace = true }
urlencoding = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }

tokio = { workspace = true, optional = true }
paste = { workspace = true, optional = true }
smallvec = { workspace = true, optional = true }
leptos_axum = { workspace = true, optional = true }
http = { workspace = true, optional = true }
