# debug = true
# log_dir = "~/.flams/log"
# temp_dir = "~/.flams/tmp"
# database = "~/.flams/users.sqlite"

[server]
# port = 8095
# ip = "127.0.0.1"
# admin_pwd = "foobar"
# external_url = "https://mathhub.info"

[buildqueue]
# num_threads=6

[gitlab]
# url = "https://mathhub.info"
# token = "SECRET_TOKEN"
# app_id = "APP_ID"
# app_secret = "APP_SECRET"
# redirect_url = "http://localhost:3000"
