# debug = true
# log_dir = "~/.immt/log"
# temp_dir = "~/.immt/tmp"
# database = "~/.immt/users.sqlite"

[server]
# port = 3000
# ip = "127.0.0.1"
# admin_pwd = "foobar"

[buildqueue]
# num_threads=6

[gitlab]
# url = "https://gl.mathhub.info"
# token = "SECRET_TOKEN"
# app_id = "APP_ID"
# app_secret = "APP_SECRET"
# redirect_url = "http://localhost:3000"