[package]
name = "ftml-viewer"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[features]
ssr = [] # just to make documentation happy
ts = ["ftml-viewer-components/ts","dep:tsify-next","dep:serde","flams-utils/wasm","dep:wasm-bindgen-futures","flams-ontology/wasm"]
omdoc = ["ftml-viewer-components/omdoc"]

[dependencies]
ftml-viewer-components = {workspace=true,features = ["csr"]}
flams-web-utils = {workspace=true,features=["csr"]}
leptos-dyn-dom = {workspace=true,features = ["csr"]}
leptos = {workspace=true,features = ["csr"]}
leptos_meta = {workspace=true}
wasm-bindgen = {workspace=true}
console_error_panic_hook = {workspace=true}
thaw = {workspace=true}
tracing-wasm = {workspace=true}
tracing = {workspace=true,features=["release_max_level_info"]}

flams-utils = {workspace=true}
tsify-next = {workspace=true,optional = true}
serde = {workspace=true,optional=true}
flams-ontology = {workspace=true}
wasm-bindgen-futures = {workspace=true,optional=true}


#tachys = {workspace = true}
#leptos_macro = {workspace = true}
#tachys = {version="=0.1.0-beta5"}
#reactive_graph = {version="=0.1.0-beta5"}
#leptos_macro = {version="=0.7.0-beta5"}
#hydration_context = {version="=0.2.0-beta5"}
#leptos_config = {version="=0.7.0-beta5"}

