[tasks.wasm-pack]
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build","--target","no-modules","--out-name","ftml",
    "--","--target","wasm32-unknown-unknown","-Z","build-std=std,panic_abort,core,alloc","-Z","build-std-features=optimize_for_size,panic_immediate_abort"
]

[tasks.wasm-pack-ts]
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build","--out-dir","ts","--","--features","ts,omdoc",
    "--target","wasm32-unknown-unknown","-Z","build-std=std,panic_abort,core,alloc","-Z","build-std-features=optimize_for_size,panic_immediate_abort"
]

[tasks.ts-dev]
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build","--dev","--out-dir","ts","--","--features","ts,omdoc"]

[tasks.ts]
alias = "wasm-pack-ts"


[tasks.wasm-pack-dev]
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build","--target","no-modules","--dev"]


[tasks.update-js]
env = { "CARGO_MAKE_RUST_SCRIPT_PROVIDER" = "rust-script" }
script_runner = "@rust"
script = '''
use std::{io::Write, path::PathBuf};
fn main() {
    let old_js_file = PathBuf::from(".").join("pkg").join("ftml.js");
    let js_file = old_js_file.clone(); //PathBuf::from(".").join("pkg").join("ftml.js");
    let jv = std::fs::read_to_string(&old_js_file).unwrap();
    std::fs::File::create(js_file).unwrap().write_all(format!(r#"{jv}
const {{ run, set_server_url }} = wasm_bindgen;

{}

window.FLAMS_SERVER_URL = "https://flams.mathhub.info";

var PRIVATE__do_ftml_on_start = () => {{}};
function ftml_on_start(f) {{
    let old = PRIVATE__do_ftml_on_start;
    PRIVATE__do_ftml_on_start = () => {{
        old();
        f();
    }};
}}

async function ftml_start() {{
    await wasm_bindgen();
    PRIVATE__do_ftml_on_start();
}}
ftml_start();
    "#,
    include_str!("../../../../source/ftml/viewer-components/ftml-top.js")
        .replace("export function","function")
    ).as_bytes()).unwrap();
}
'''

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
dependencies = ["wasm-pack","update-js"]

[tasks.build-dev]
dependencies = ["wasm-pack-dev","update-js"]

[tasks.default]
alias = "build"