[package]
name = "ftml-solver-trace"
version = "0.0.1"
edition = "2024"

[lints]
workspace = true

[features]
full = []
colors=["dep:owo-colors","full"]

[dependencies]
ftml-uris = {workspace = true}
ftml-ontology = {workspace = true}
serde = {workspace = true}
serde_stacker = {workspace = true}
serde_json = {workspace = true}

owo-colors = {version="4",features=["supports-colors"],optional=true}
