[package]
name = "shtml-viewer-components"
version = "0.0.1"
edition = "2021"

[lints]
workspace = true

[features]
omdoc = ["dep:icondata_ai","dep:gloo-storage"]
ts = ["dep:tsify-next","immt-utils/wasm"]
rdf = ["immt-ontology/rdf","shtml-extraction/rdf"]
csr = ["leptos-dyn-dom/csr","leptos/csr","dep:reqwasm"]
hydrate= ["omdoc","leptos-dyn-dom/hydrate","leptos/hydrate","immt-web-utils/hydrate"]
ssr = ["leptos/ssr","rdf","immt-web-utils/ssr","dep:immt-system","dep:tokio"]

[dependencies]
leptos-dyn-dom = {workspace=true}
leptos = {workspace=true}
thaw = {workspace=true}
shtml-extraction = {workspace=true}
immt-ontology = {workspace=true,features=["serde"]}
immt-system = {workspace=true, optional=true}
tokio = {workspace = true,optional=true}
immt-utils = {workspace=true}
smallvec = {workspace=true}
tracing = {workspace=true}
lazy_static = {workspace=true}
immt-web-utils = {workspace=true}
urlencoding = {workspace=true}
send_wrapper = {workspace=true}
wasm-bindgen = {workspace=true}
serde = {workspace = true,features=["derive"]}
either = {workspace = true, features=["serde"]}
icondata_bi = {workspace = true}
icondata_ai = {workspace = true,optional=true}
gloo-storage = {workspace = true,optional=true}

web-sys = {workspace = true,features=["ScrollIntoViewOptions","ScrollLogicalPosition"]} 

# csr
reqwasm = {workspace=true,optional=true}
#reqwest = {workspace=true,optional=true}

tsify-next = {workspace = true,optional=true}





#tachys = {workspace = true}
#leptos_macro = {workspace = true}
#tachys = {version="=0.1.0-beta5"}
#reactive_graph = {version="=0.1.0-beta5"}
#leptos_macro = {version="=0.7.0-beta5"}
#hydration_context = {version="=0.2.0-beta5"}
#leptos_config = {version="=0.7.0-beta5"}