[target.wasm32-unknown-unknown]
rustflags = [
    "-Ctarget-cpu=mvp",
    "-Ctarget-feature=+multivalue,+mutable-globals,+reference-types,+sign-ext",
    "--cfg", "web_sys_unstable_apis",
    "--cfg", 'getrandom_backend="wasm_js"'
]

[build]
rustflags = ["--cfg", "tokio_unstable","--cfg","web_sys_unstable_apis"]

#[unstable]
#codegen-backend=true

#[profile.server-dev]
#codegen-backend = "cranelift"

#[target.x86_64-unknown-linux-gnu]
#linker="clang"
#rustflags = ["-C","link-arg=-fuse-ld=/usr/bin/mold"]

# ---------------------------------------------------------

#[target.x86_64-pc-windows-msvc]
#target-dir = "target"

#[unstable]
#build-std = ["std", "panic_abort", "core", "alloc"]
#build-std-features = ["panic_immediate_abort"]

