[build]
rustflags = ["--cfg", "tokio_unstable","--cfg","web_sys_unstable_apis"]

#[target.x86_64-pc-windows-msvc]
#target-dir = "target"

#[unstable]
#build-std = ["std", "panic_abort", "core", "alloc"]
#build-std-features = ["panic_immediate_abort"]