
[package]
name = "flams-router-git-components"
version = "0.0.1"
edition = "2024"

[lints]
workspace = true

[features]
ssr = [
    "leptos/ssr",
    "ftml-component-utils/ssr",
    "flams-router-git-base/ssr",
    #"flams-router-base/ssr",
    "flams-web-utils/ssr",
    "flams-router-buildqueue-base/ssr",
    #"dep:tokio",
]
hydrate = [
    "leptos/hydrate",
    "ftml-component-utils/hydrate",
    "flams-router-git-base/hydrate",
    "flams-web-utils/hydrate",
    "flams-router-buildqueue-base/hydrate",
    #"flams-router-base/hydrate",
]
docs-only = []

[dependencies]
ftml-ontology = { workspace = true, features = ["serde"] }
ftml-uris = { workspace = true, features = ["serde"] }

flams-backend-types = { workspace = true }

flams-router-git-base = { workspace = true }
flams-utils = { workspace = true }
flams-git = { workspace = true }
flams-web-utils = { workspace = true }
#flams-router-base = { workspace = true }
#flams-system = { workspace = true, optional = true }
flams-router-buildqueue-base = { workspace = true }
flams-router-base = {workspace = true}

leptos = { workspace = true }
leptos_router = { workspace = true }
#leptos_router = { workspace = true }
ftml-component-utils = {workspace = true}
serde = { workspace = true }
#tracing = { workspace = true }
#tokio = { workspace = true, optional = true }
