[package]
name = "flams-stex"
version = "0.0.1"
edition = "2021"

[dev-dependencies]
tracing-subscriber = { workspace = true }
rstest = { workspace = true }

[dependencies]
ftml-ontology = { workspace = true, features = ["serde"] }
ftml-uris = { workspace = true }

flams-ftml = { workspace = true }
flams-system = { workspace = true }
flams-utils = { workspace = true, features = ["serde"] }
ftml-solver = {workspace = true}

flams-math-archives = { workspace = true }

rustex_lib = { workspace = true }
tex_engine = { workspace = true }

chrono = { workspace = true }
tracing = { workspace = true, features = ["log"] }
parking_lot = { workspace = true }
paste = { workspace = true }
either = { workspace = true }
regex = { workspace = true }
smallvec = { workspace = true }
eyre = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
