[package]
name = "immt-stex"
version = "0.0.1"
edition = "2021"

[dependencies]
immt-shtml = {workspace=true}
immt-ontology = {workspace=true}
immt-system = {workspace=true}
immt-utils = {workspace=true}

RusTeX = {workspace=true}
tex_engine = {workspace=true}

chrono = {workspace = true}
tracing = {workspace = true}
parking_lot = {workspace = true}
paste = {workspace = true}
either = {workspace = true}

[lints]
workspace = true
