[package]
name = "immt-shtml"
version = "0.0.1"
edition = "2021"

[dependencies]
immt-ontology = {workspace=true,features=["serde"]}
immt-system = {workspace=true}
immt-utils = {workspace=true}
shtml-extraction = {workspace=true,features = ["rdf","full"]}
either = {workspace=true}
html5ever = {workspace=true}
lazy_static = {workspace=true}
serde = {workspace=true}
bincode = {workspace=true}
tex_engine = {workspace=true}

[lints]
workspace = true
