[package]
name = "flams-ftml"
version = "0.0.1"
edition = "2021"

[dependencies]
ftml-uris = { workspace = true, features = ["serde"] }
ftml-ontology = { workspace = true, features = ["serde"] }
ftml-parser = { workspace = true, features = ["rdf"] }
ftml5ever = { workspace = true }

flams-system = { workspace = true }
flams-utils = { workspace = true }

flams-math-archives = { workspace = true }

either = { workspace = true }
#html5ever = { workspace = true }
#lazy_static = { workspace = true }
serde = { workspace = true }
# bincode = { workspace = true }
tex_engine = { workspace = true }
phf = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
