[package]
name = "flams-ftml"
version = "0.0.1"
edition = "2021"

[features]
tokio = ["flams-system/tokio", "dep:tokio"]
git = ["flams-system/gitlab", "dep:flams-git"]

[dependencies]
flams-ontology = { workspace = true, features = ["serde"] }
flams-system = { workspace = true }
flams-utils = { workspace = true }
flams-git = { workspace = true, optional = true }
ftml-extraction = { workspace = true, features = ["rdf", "full"] }

either = { workspace = true }
html5ever = { workspace = true }
lazy_static = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
tex_engine = { workspace = true }
phf = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
parking_lot = { workspace = true }
dashmap = { workspace = true }
rustc-hash = { workspace = true }
git-url-parse = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true, optional = true }
reqwest = { workspace = true, features = ["blocking"] }

[lints]
workspace = true
