[build]
target = "wasm32-unknown-unknown"

[env]
RUSTFLAGS = {value="--cfg=web_sys_unstable_apis",force=true}

[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["optimize_for_size","panic_immediate_abort"]