
[package]
name = "flams-router-buildqueue-components"
version = "0.0.1"
edition = "2024"

[lints]
workspace = true

[features]
ssr = [
    "leptos/ssr",
    "thaw/ssr",
    "ftml-dom/ssr",
    "flams-router-base/ssr",
    "flams-router-buildqueue-base/ssr",
    "flams-router-git-base/ssr",
    "flams-router-content/ssr",
    "flams-web-utils/ssr",
    "dep:flams-system",
    "dep:tokio",
]
hydrate = [
    "leptos/hydrate",
    "thaw/hydrate",
    "ftml-dom/hydrate",
    "flams-web-utils/hydrate",
    "flams-router-base/hydrate",
    "flams-router-buildqueue-base/hydrate",
    "flams-router-git-base/hydrate",
    "flams-router-content/hydrate",
]
docs-only = []

[dependencies]
ftml-uris = { workspace = true, features = ["serde"] }
ftml-ontology = { workspace = true, features = ["serde"] }
ftml-dom = { workspace = true }
ftml-components = {workspace = true}

flams-backend-types = { workspace = true }

flams-utils = { workspace = true }
flams-git = { workspace = true }
flams-web-utils = { workspace = true }
flams-router-base = { workspace = true }
flams-router-content = {workspace = true}
flams-router-buildqueue-base = { workspace = true }
flams-router-git-base = { workspace = true }
flams-system = { workspace = true, optional = true }

either = {workspace = true}
leptos = { workspace = true }
leptos_router = { workspace = true }
thaw = { workspace = true }
serde = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, optional = true }
icondata_tb = { workspace = true }
