[package]
name = "flams-experiments"
version = "0.0.1"
edition = "2021"
description = "𝖥𝖫∀𝖬∫ - Flexiformal Annotation Management System"

[lib]
crate-type = ["cdylib", "rlib"]

[features]

[dev-dependencies]
rstest = { workspace = true }


[lints]
workspace = true

[dependencies]
ftml-uris = { workspace = true, features = ["serde", "tantivy"] }
ftml-ontology = { workspace = true, features = ["serde"] }

flams-utils = { workspace = true, features = ["serde", "tokio"] }
flams-system = { workspace = true }
flams-lsp = { workspace = true, features = ["ws"] }
flams-stex = { workspace = true }
flams-ftml = { workspace = true }
flams-git = { workspace = true, features = ["git2"] }
git2 = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true, features = ["full", "rt", "rt-multi-thread"] }
lazy_static = { workspace = true }
color-eyre = { workspace = true }

html2text = { workspace = true }
tantivy = { workspace = true }
url = { workspace = true }

git-url-parse = { workspace = true }
