[package]
name = "flams-router-vscode"
version = "0.0.1"
edition = "2024"

[lints]
workspace = true

[features]
ssr = [
    "leptos/ssr",
    "leptos_router/ssr",
    "ftml-components/ssr",
    "ftml-dom/ssr",
    "flams-web-utils/ssr",
    "flams-router-login/ssr",
    "flams-router-content/ssr",
    "dep:flams-system",
]
hydrate = [
    "leptos/hydrate",
    "ftml-components/hydrate",
    "ftml-dom/hydrate",
    "flams-router-login/hydrate",
    "flams-web-utils/hydrate",
    "flams-router-content/hydrate",
    "dep:wasm-bindgen",
    "dep:serde-wasm-bindgen",
]
docs-only = []

[dependencies]
ftml-components = { workspace = true }
ftml-dom = { workspace = true }

flams-web-utils = { workspace = true }
flams-router-login = { workspace = true }
flams-router-base = {workspace = true}
flams-router-content = { workspace = true }
flams-utils = { workspace = true }
flams-system = { workspace = true, optional = true }

leptos = { workspace = true }
leptos_router = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
serde-wasm-bindgen = { workspace = true, optional = true }

serde = { workspace = true }
