[build]
target = "wasm32-unknown-unknown"
rustflags = [
    #"-Z","build-std=std,panic_abort,core,alloc",
    #"-Z","build-std-features=optimize_for_size,panic_immediate_abort",
    "-Cstrip=debuginfo"
]
[unstable]
build-std = ["std","panic_abort","core", "alloc"]
build-std-features = ["optimize_for_size","panic_immediate_abort"]