[package]
name = "immt-stex"
version = "0.0.1"
authors = ["Dennis Müller <d.mueller@kwarc.info>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = """

"""
edition = "2021"

[profile.release]
opt-level = 2
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.dev.package.RusTeX]
opt-level = 2

[profile.dev.package.tex_engine]
opt-level = 2

[lib]
crate-type = ["lib"]
path = "src/lib.rs"

[dev-dependencies]
tracing-subscriber = { version="0.3",features = ["smallvec","parking_lot"] }

[dependencies]
# immt-api = {path = "../api"}
immt-system = {path = "../system"}
immt-shtml = {path = "../shtml"}
either = "1.10"
tracing = "0.1"
paste = "1.0"
async-trait = "0.1"
RusTeX = {path= "../../RusTeXNew/rustex",features = ["multithreaded"]}
tex_engine = {path= "../../RusTeXNew/tex_engine",features = ["multithreaded"]}
parking_lot = "0.12"
chrono = "0.4"

# ------------------------------
immt-api = {path = "../api", features = ["pariter","tokio"]}
rayon = "1.8.1"