[package]
name = "flams-router-search"
version = "0.0.1"
edition = "2024"

[lints]
workspace = true

[features]
ssr = [
    "leptos/ssr",
    "leptos_router/ssr",
    "ftml-component-utils/ssr",
    "ftml-components/ssr",
    "flams-web-utils/ssr",
    "flams-router-vscode/ssr",
    "flams-router-content/ssr",
    "dep:flams-system",
    "dep:flams-math-archives",
    "dep:flams-search",
    "dep:tokio",
    #"dep:paste",
    #"dep:smallvec",
]
hydrate = [
    "leptos/hydrate",
    "ftml-component-utils/hydrate",
    "ftml-components/hydrate",
    "flams-router-vscode/hydrate",
    "flams-router-content/hydrate",
    "flams-web-utils/hydrate",
    #"dep:reqwasm",
]
docs-only = []
vectorsearch = ["flams-backend-types/vectorsearch"]

[dependencies]
ftml-uris = { workspace = true, features = ["leptos"] }
ftml-ontology = { workspace = true, features = ["serde"] }
ftml-components = { workspace = true }
ftml-dom = { workspace = true }

flams-utils = { workspace = true }
flams-web-utils = { workspace = true }
flams-router-base = { workspace = true }
flams-router-vscode = { workspace = true }
flams-router-content = { workspace = true }
flams-backend-types = { workspace = true, features = ["serde"] }
flams-math-archives = { workspace = true, optional = true }
flams-system = { workspace = true, optional = true }
flams-search = { workspace = true, optional = true }

leptos = { workspace = true }
leptos_router = { workspace = true }
ftml-component-utils = {workspace = true}
serde = { workspace = true }

tokio = { workspace = true, optional = true }
#reqwasm = { workspace = true, optional = true }
#paste = { workspace = true, optional = true }
#smallvec = { workspace = true, optional = true }
#lazy_static = { workspace = true }
